# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wjiang的博客
brief-intro: a postgraduate learning NLP
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hmjw.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
QQ: 767257113
github_username:  hmjw
email: 762757113@QQ.com

description_footer: 来自wjiang的个人博客！

# comments
# gitalk
gitalk: enable
clientID: 1bbeac5e740f287e5b6f
clientSecret: 7ce61276b006fca919dd4b08f0c086c81a6176ca
repo: hmjw.github.io
owner: hmjw
admin: hmjw

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "https://hm.baidu.com/hm.js?2a0c665a3e9bb5c825020fc3b4d09a32";
# xxxxx字符串
baidu_tongji_id: 2a0c665a3e9bb5c825020fc3b4d09a32
google_analytics_id: UA-131008981-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
port: 4001
